### ISSUE TITLE
Getting exception while running the app

### ISSUE THREAD

**Issue by anil1712** [aviklai/libtiffjs#4]
Hi,

I am getting this exception while running the app

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': Response object could not be cloned.
    at eval (webpack-internal:///../node_modules/libtiffjs/lib/index.js:1:1955)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///../node_modules/libtiffjs/lib/index.js:1:1783)

DevTools failed to load SourceMap: Could not load content for https://localhost:3000/libtiff-worker.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Please help me to get out of it

**Comment by aviklai** [comment]
@anil1712 Hi, 
Can you please create a codesandbox for this error?

**Comment by anil1712** [comment]
@aviklai Here also its not working

https://libtiffjs.netlify.app


```

[Violation] 'message' handler took 4452ms
DevTools failed to load SourceMap: Could not load content for https://libtiffjs.netlify.app/libtiff-worker.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE


index.js?450e:1 Uncaught (in promise) Error: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': ArrayBuffer is not detachable and could not be cloned.
    at Worker.t.data.ready.n.onmessage (index.js?450e:1)
```

**Comment by anil1712** [comment]
@aviklai I am trying to create the codesandbox but I am getting the dependency related exception there.
Here is the link for the same

https://codesandbox.io/s/trusting-morning-qolyc

**Comment by aviklai** [comment]
@anil1712 Hi,

It looks like a change in chrome.
Just checked in firefox and it works:
https://libtiffjs.netlify.app/

I will look into it later today and I will update here.

**Comment by aviklai** [comment]
@anil1712 Hi,

Fixed and released a new version.
The demo works as well:
https://libtiffjs.netlify.app/
